### ISSUE TITLE
Swap out the door puzzle somewhere else

### ISSUE THREAD

**Issue by lazerwalker** [lazerwalker/azure-mystery-mansion#27]
The hardest and  most likely to fail question shouldn't be first?

**Comment by jlooper** [comment]
I did tweak the numbers on this to align with Learn. maybe if we gave one solid hint, the rest would fall in place?

**Comment by lazerwalker** [comment]
Yeah, my instinct is we can replace the "1", "2", and "3" hints with matching symbols. e.g. somebody's hand-scribbled a circle, triangle, and square over the 3 dials, and the same shapes show up in the post-its.
