### ISSUE TITLE
Brainstorm alternate modules for puzzle 1

### ISSUE THREAD

**Issue by lazerwalker** [lazerwalker/azure-mystery-mansion#30]
Might be good to find some numbers that are less likely to change over time, thus breaking the game/puzzle.

**Comment by jlooper** [comment]
The roles question is hard to decipher right now. I recommend: https://docs.microsoft.com/en-us/learn/certifications/ and ask how many roles for certification are listed

**Comment by jlooper** [comment]
I've edited this puzzle since the solution has changed; we can revisit.
